%YAML 1.2
---

# Данные для подключения к серверу.
server:
  host: 100.100.100.100    # IP-адрес ftp-сервера.
  port: 21                 # ftp-порт.
  username: user           # Логин для авторизации на сервере.
  password: long_password  # Пароль для авторизации на сервере.
  pasv_mode: True          # Режим подключения к серверу (по умолчанию Пассивный режим).

# Данные для чтения из терминала.
read:
  fmt_date: '%Y-%m-%d'  # Формат вводимой даты.
  fmt_time: '%H:%M'     # Формат вводимого времени.

# Начало и конец временного промежутка по умолчанию.
# Используется в режиме работы программы по датам, если промежуток не указан.
std_time:
  begin_weekday: '11:00'  # Начало промежутка в будний день.
  end_weekday:   '21:00'  # Конец промежутка в будний день.
  begin_weekend: '10:00'  # Начало промежутка в выходной день.
  end_weekend:   '21:00'  # Конец промежутка в выходной день.

# Данные для записи отчёта.
write:
  path: /your/path/xml2csv/reports  # Путь для сохранения отчёта.

  fmt_date: '%Y-%m-%d'  # Формат даты в отчёте.
  fmt_time: '%H:%M'     # Формат времени в отчёте.
  csv_name: report      # Начало имени отчёта.
  csv_delim: ;          # Раделитель, используемый в отчёте.

  csv_flds:  # Названия полей в отчёте.
    file:    # Режим работы по файлам.
    - name             # Имя камеры.
    - date(date_from)  # Дата начала измерения.
    - time(date_from)  # Время начала измерения.
    - date(date_to)    # Дата конца измерения.
    - time(date_to)    # Время конца измерения.
    - granularity      # Промежуток измерения в секундах.
    - line_name        # Имя локации.
    - fw_count         # Количество вошедших людей.
    - bw_count         # Количество вышедших людей.
    date:    # Режим работы по файлам.
    - date       # Дата.
    - time_from  # Время начала измерения.
    - time_to    # Время конца измерения.
    - fw_count   # Количество вошедших людей за день.
    - bw_count   # Количество вышедших людей за день.
